/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#define RCC_AHB2ENR (uint32_t*)0x44020C8C
#define GPIOA_MODER (uint32_t*)0x42020000
#define GPIOB_MODER (uint32_t*)0x42020400
#define GPIOE_MODER (uint32_t*)0x42021000
#define GPIOG_MODER (uint32_t*)0x42021800

#define GPIOA_ODR (uint32_t*)0x42020014
#define GPIOB_ODR (uint32_t*)0x42020414
#define GPIOG_ODR (uint32_t*)0x42021814
#define GPIOE_ODR (uint32_t*)0x42021014

#define GPIOE_IDR (uint32_t*)0x42021010
#define GPIOG_IDR (uint32_t*)0x42021810

#define GPIOE_PUPDR (uint32_t*)0x4202100C
#define GPIOG_PUPDR (uint32_t*)0x4202180C

void keypad_init() {}

void LCD_init() {}

void blink_n_times(int n) {
	for (int i = 0; i < n; ++i) {
		*GPIOA_ODR |= (1 << 6);
		for (int i = 0; i < 1000000; ++i);

		*GPIOA_ODR &= ~(1 << 6);
		for (int i = 0; i < 1000000; ++i);
	}
}

int main(void)
{
	*RCC_AHB2ENR |= (1 << 0);
	*RCC_AHB2ENR |= (1 << 1);
	*RCC_AHB2ENR |= (1 << 4);
	*RCC_AHB2ENR |= (1 << 6);

	*GPIOA_MODER &= ~(0x3 << 12);
	*GPIOA_MODER |= (1 << 12);

	*GPIOB_MODER &= ~(0xF << 12);
	*GPIOB_MODER |= (0x5 << 12);
	*GPIOG_MODER &= ~(0x3 << 28);
	*GPIOG_MODER |= (1 << 28);
	*GPIOE_MODER &= ~(0x3 << 26);
	*GPIOE_MODER |= (1 << 26);

	*GPIOE_MODER &= ~(0x3 << 28);
	*GPIOE_MODER &= ~(0x3 << 22);
	*GPIOE_MODER &= ~(0x3 << 18);
	*GPIOG_MODER &= ~(0x3 << 24);

	*GPIOE_PUPDR &= ~(0x3 << 28);
	*GPIOE_PUPDR |= (1 << 29);
	*GPIOE_PUPDR &= ~(0x3 << 22);
	*GPIOE_PUPDR |= (1 << 23);
	*GPIOE_PUPDR &= ~(0x3 << 18);
	*GPIOE_PUPDR |= (1 << 19);
	*GPIOG_PUPDR &= ~(0x3 << 24);
	*GPIOG_PUPDR |= (1 << 25);


	for(;;) {
		*GPIOB_ODR |= (1 << 7);
		if (*GPIOE_IDR & (1 << 14)) {

		} else if (*GPIOE_IDR & (1 << 11)) {

		} else if (*GPIOE_IDR & (1 << 9)) {

		} else if (*GPIOG_IDR & (1 << 12)) {

		}
		*GPIOB_ODR &= ~(1 << 7);

		*GPIOB_ODR |= (1 << 6);
		if (*GPIOE_IDR & (1 << 14)) {

		} else if (*GPIOE_IDR & (1 << 11)) {

		} else if (*GPIOE_IDR & (1 << 9)) {

		} else if (*GPIOG_IDR & (1 << 12)) {

		}
		*GPIOB_ODR &= ~(1 << 6);

		*GPIOG_ODR |= (1 << 14);
		if (*GPIOE_IDR & (1 << 14)) {

		} else if (*GPIOE_IDR & (1 << 11)) {

		} else if (*GPIOE_IDR & (1 << 9)) {

		} else if (*GPIOG_IDR & (1 << 12)) {

		}
		*GPIOG_ODR &= ~(1 << 14);

		*GPIOE_ODR |= (1 << 13);
		if (*GPIOE_IDR & (1 << 14)) {
			blink_n_times(1);
		} else if (*GPIOE_IDR & (1 << 11)) {
			blink_n_times(2);
		} else if (*GPIOE_IDR & (1 << 9)) {
			blink_n_times(3);
		} else if (*GPIOG_IDR & (1 << 12)) {
			blink_n_times(4);
		}
		*GPIOE_ODR &= ~(1 << 13);
	}

}
