/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

/*
 * RS PA6
 * RW PC0
 * E PC3
 * DB7 PF3
 * DB6 PD15
 * DB5 PD14
 * DB4 PB5
 * DB3 PG9
 * DB2 PA5
 * DB1 PB9
 * DB0 PB8
 */

#include <stdint.h>
#include <stdio.h>
#include <ctype.h>

#define RCC_AHB2ENR (uint32_t*)0x44020C8C
#define GPIOA_MODER (uint32_t*)0x42020000
#define GPIOB_MODER (uint32_t*)0x42020400
#define GPIOC_MODER (uint32_t*)0x42020800
#define GPIOD_MODER (uint32_t*)0x42020C00
#define GPIOE_MODER (uint32_t*)0x42021000
#define GPIOF_MODER (uint32_t*)0x42021400
#define GPIOG_MODER (uint32_t*)0x42021800

#define GPIOA_ODR (uint32_t*)0x42020014
#define GPIOB_ODR (uint32_t*)0x42020414
#define GPIOC_ODR (uint32_t*)0x42020814
#define GPIOD_ODR (uint32_t*)0x42020C14
#define GPIOE_ODR (uint32_t*)0x42021014
#define GPIOF_ODR (uint32_t*)0x42021414
#define GPIOG_ODR (uint32_t*)0x42021814

#define GPIOA_IDR (uint32_t*)0x42020010
#define GPIOB_IDR (uint32_t*)0x42020410
#define GPIOD_IDR (uint32_t*)0x42020C10
#define GPIOE_IDR (uint32_t*)0x42021010
#define GPIOF_IDR (uint32_t*)0x42021410
#define GPIOG_IDR (uint32_t*)0x42021810

#define GPIOE_PUPDR (uint32_t*)0x4202100C
#define GPIOG_PUPDR (uint32_t*)0x4202180C

void keypad_init() {
	*RCC_AHB2ENR |= (1 << 0);
	*RCC_AHB2ENR |= (1 << 1);
	*RCC_AHB2ENR |= (1 << 4);
	*RCC_AHB2ENR |= (1 << 6);

	*GPIOA_MODER &= ~(0x3 << 12);
	*GPIOA_MODER |= (1 << 12);

	*GPIOB_MODER &= ~(0xF << 12);
	*GPIOB_MODER |= (0x5 << 12);
	*GPIOG_MODER &= ~(0x3 << 28);
	*GPIOG_MODER |= (1 << 28);
	*GPIOE_MODER &= ~(0x3 << 26);
	*GPIOE_MODER |= (1 << 26);

	*GPIOE_MODER &= ~(0x3 << 28);
	*GPIOE_MODER &= ~(0x3 << 22);
	*GPIOE_MODER &= ~(0x3 << 18);
	*GPIOG_MODER &= ~(0x3 << 24);

	*GPIOE_PUPDR &= ~(0x3 << 28);
	*GPIOE_PUPDR |= (1 << 29);
	*GPIOE_PUPDR &= ~(0x3 << 22);
	*GPIOE_PUPDR |= (1 << 23);
	*GPIOE_PUPDR &= ~(0x3 << 18);
	*GPIOE_PUPDR |= (1 << 19);
	*GPIOG_PUPDR &= ~(0x3 << 24);
	*GPIOG_PUPDR |= (1 << 25);
}

void LCD_write_init() {
	*GPIOF_MODER &= ~(0x3 << 6);
	*GPIOF_MODER |= (1 << 6);
	*GPIOD_MODER &= ~(0xF << 28);
	*GPIOD_MODER |= (0x5 << 28);
	*GPIOB_MODER &= ~(0x3 << 10);
	*GPIOB_MODER |= (1 << 10);
	*GPIOG_MODER &= ~(0x3 << 18);
	*GPIOG_MODER |= (1 << 18);
	*GPIOA_MODER &= ~(0x3 << 10);
	*GPIOA_MODER |= (1 << 10);
	*GPIOB_MODER &= ~(0xF << 16);
	*GPIOB_MODER |= (0x5 << 16);
}

void LCD_init() {
	*RCC_AHB2ENR |= (1 << 2);
	*RCC_AHB2ENR |= (1 << 3);
	*RCC_AHB2ENR |= (1 << 5);

	*GPIOA_MODER &= ~(0x3 << 12);
	*GPIOA_MODER |= (1 << 12);
	*GPIOC_MODER &= ~(0x3 << 0);
	*GPIOC_MODER |= (1 << 0);
	*GPIOC_MODER &= ~(0x3 << 6);
	*GPIOC_MODER |= (1 << 6);
	LCD_write_init();
}

void LCD_read_init() {
	*GPIOF_MODER &= ~(0x3 << 6);
	*GPIOD_MODER &= ~(0xF << 28);
	*GPIOB_MODER &= ~(0x3 << 10);
	*GPIOG_MODER &= ~(0x3 << 18);
	*GPIOA_MODER &= ~(0x3 << 10);
	*GPIOB_MODER &= ~(0xF << 16);
}

void wait_while_busy() {
	LCD_read_init();
	*GPIOA_ODR &= ~(1 << 6);
	*GPIOC_ODR |= (1 << 0);
	while (1) {
		*GPIOC_ODR |= (1 << 3);
		for (int i = 0; i < 50; ++i);

		if (!(*GPIOF_IDR & (1 << 3))) {
			*GPIOC_ODR &= ~(1 << 3);
			break;
		}

		*GPIOC_ODR &= ~(1 << 3);
	}
	LCD_write_init();
}


char keypad_response() {
	// First Row | 1 | 2 | 3 | A |
	*GPIOB_ODR |= (1 << 7);
	if (*GPIOE_IDR & (1 << 14)) {
		*GPIOB_ODR &= ~(1 << 7);
		return '1';
	} else if (*GPIOE_IDR & (1 << 11)) {
		*GPIOB_ODR &= ~(1 << 7);
		return '2';
	} else if (*GPIOE_IDR & (1 << 9)) {
		*GPIOB_ODR &= ~(1 << 7);
		return '3';
	} else if (*GPIOG_IDR & (1 << 12)) {
		*GPIOB_ODR &= ~(1 << 7);
		return 'A';
	}
	*GPIOB_ODR &= ~(1 << 7);

	// Second Row | 4 | 5 | 6 | B |
	*GPIOB_ODR |= (1 << 6);
	if (*GPIOE_IDR & (1 << 14)) {
		*GPIOB_ODR &= ~(1 << 6);
		return '4';
	} else if (*GPIOE_IDR & (1 << 11)) {
		*GPIOB_ODR &= ~(1 << 6);
		return '5';
	} else if (*GPIOE_IDR & (1 << 9)) {
		*GPIOB_ODR &= ~(1 << 6);
		return '6';
	} else if (*GPIOG_IDR & (1 << 12)) {
		*GPIOB_ODR &= ~(1 << 6);
		return 'B';
	}
	*GPIOB_ODR &= ~(1 << 6);

	// Third Row | 7 | 8 | 9 | C |
	*GPIOG_ODR |= (1 << 14);
	if (*GPIOE_IDR & (1 << 14)) {
		*GPIOG_ODR &= ~(1 << 14);
		return '7';
	} else if (*GPIOE_IDR & (1 << 11)) {
		*GPIOG_ODR &= ~(1 << 14);
		return '8';
	} else if (*GPIOE_IDR & (1 << 9)) {
		*GPIOG_ODR &= ~(1 << 14);
		return '9';
	} else if (*GPIOG_IDR & (1 << 12)) {
		*GPIOG_ODR &= ~(1 << 14);
		return 'C';
	}
	*GPIOG_ODR &= ~(1 << 14);

	// Fourth Row | * | 0 | # | D |
	*GPIOE_ODR |= (1 << 13);
	if (*GPIOE_IDR & (1 << 14)) {
		*GPIOE_ODR &= ~(1 << 13);
		return '*';
	} else if (*GPIOE_IDR & (1 << 11)) {
		*GPIOE_ODR &= ~(1 << 13);
		return '0';
	} else if (*GPIOE_IDR & (1 << 9)) {
		*GPIOE_ODR &= ~(1 << 13);
		return '#';
	} else if (*GPIOG_IDR & (1 << 12)) {
		*GPIOE_ODR &= ~(1 << 13);
		return 'D';
	}
	*GPIOE_ODR &= ~(1 << 13);

	return '-';
}

int length(int num) {
	int result = 0;
	while (num > 0) {
		result += 1;
		num /= 10;
	}
	return result;
}

void delay() {
	for (int i = 0; i < 50000; ++i);
}

void pulse() {
	*GPIOC_ODR |= (1 << 3);
	for (int i = 0; i < 5000; ++i);
	*GPIOC_ODR &= ~(1 << 3);
}

void clear_bus() {
	*GPIOA_ODR &= ~(1 << 6);
	*GPIOC_ODR &= ~(1 << 0);
	*GPIOF_ODR &= ~(1 << 3);
	*GPIOD_ODR &= ~(1 << 15);
	*GPIOD_ODR &= ~(1 << 14);
	*GPIOB_ODR &= ~(1 << 5);
	*GPIOG_ODR &= ~(1 << 9);
	*GPIOA_ODR &= ~(1 << 5);
	*GPIOB_ODR &= ~(1 << 9);
	*GPIOB_ODR &= ~(1 << 8);
}

void write_to_IR(int rw, int db7, int db6, int db5, int db4, int db3, int db2, int db1, int db0) {
	clear_bus();
	*GPIOC_ODR |= (rw << 0);
	*GPIOF_ODR |= (db7 << 3);
	*GPIOD_ODR |= (db6 << 15);
	*GPIOD_ODR |= (db5 << 14);
	*GPIOB_ODR |= (db4 << 5);
	*GPIOG_ODR |= (db3 << 9);
	*GPIOA_ODR |= (db2 << 5);
	*GPIOB_ODR |= (db1 << 9);
	*GPIOB_ODR |= (db0 << 8);
	pulse();
	wait_while_busy();
}

void write_to_DR(int rw, int db7, int db6, int db5, int db4, int db3, int db2, int db1, int db0) {
	clear_bus();
	*GPIOA_ODR |= (1 << 6);
	*GPIOC_ODR |= (rw << 0);
	*GPIOF_ODR |= (db7 << 3);
	*GPIOD_ODR |= (db6 << 15);
	*GPIOD_ODR |= (db5 << 14);
	*GPIOB_ODR |= (db4 << 5);
	*GPIOG_ODR |= (db3 << 9);
	*GPIOA_ODR |= (db2 << 5);
	*GPIOB_ODR |= (db1 << 9);
	*GPIOB_ODR |= (db0 << 8);
	pulse();
	wait_while_busy();
}

void display_num(int num) {
	if (num == 0) {
		write_to_DR(0, 0, 0, 1, 1, 0, 0, 0, 0);
	} else if (num == 1) {
		write_to_DR(0, 0, 0, 1, 1, 0, 0, 0, 1);
	} else if (num == 2) {
		write_to_DR(0, 0, 0, 1, 1, 0, 0, 1, 0);
	} else if (num == 3) {
		write_to_DR(0, 0, 0, 1, 1, 0, 0, 1, 1);
	} else if (num == 4) {
		write_to_DR(0, 0, 0, 1, 1, 0, 1, 0, 0);
	} else if (num == 5) {
		write_to_DR(0, 0, 0, 1, 1, 0, 1, 0, 1);
	} else if (num == 6) {
		write_to_DR(0, 0, 0, 1, 1, 0, 1, 1, 0);
	} else if (num == 7) {
		write_to_DR(0, 0, 0, 1, 1, 0, 1, 1, 1);
	} else if (num == 8) {
		write_to_DR(0, 0, 0, 1, 1, 1, 0, 0, 0);
	} else if (num == 9) {
		write_to_DR(0, 0, 0, 1, 1, 1, 0, 0, 1);
	}
}

void display(int num) {
	if (num <= 9 && num >= 0) {
		display_num(num);
	} else {
		display(num / 10);
		display_num(num % 10);
	}
}

void setup() {
	for (int i = 0; i < 4000000; ++i);
	clear_bus();
	*GPIOF_ODR |= (1 << 3);
	*GPIOD_ODR |= (1 << 15);
	*GPIOD_ODR |= (1 << 14);
	pulse();
	for (int i = 0; i < 200000; ++i);
	pulse();
	for (int i = 0; i < 10000; ++i);

	write_to_IR(0, 0, 0, 1, 1, 1, 0, 0, 0); // Function set
	delay();
	write_to_IR(0, 0, 0, 0, 0, 1, 1, 0, 0); // Display on/off
	delay();
	write_to_IR(0, 0, 0, 0, 0, 0, 0, 0, 1); // clear
	delay();
	write_to_IR(0, 0, 0, 0, 0, 0, 1, 1, 0); // Entry mode set
	delay();
	write_to_IR(0, 1, 0, 0, 0, 0, 0, 0, 0); // Set cursor line 1
	delay();
}

void input_handler(char r, int *a, int *b, int *state, int *mode) {
	if (r == '#') {
		write_to_IR(0, 0, 0, 0, 0, 0, 0, 0, 1); // clear
		*state = 0;
		*a = 0;
		*b = 0;
	} else if (*state == 1 && r == 'A' && *mode == 0) {
		write_to_IR(0, 0, 0, 0, 0, 0, 0, 0, 1); // clear
		write_to_IR(0, 1, 1, 0, 0, 0, 0, 0, 0); // cursor bottom
		display((*a) + (*b));
		*state = 2;
		*a = 0;
		*b = 0;
	} else if (*state == 0 && r == 'A') {
		write_to_IR(0, 0, 0, 0, 0, 0, 0, 0, 1); // clear
		*mode = 0;
		*state = 1;
	} else if (*state == 1 && r == '*' && *mode == 2) {
		write_to_IR(0, 0, 0, 0, 0, 0, 0, 0, 1); // clear
		write_to_IR(0, 1, 1, 0, 0, 0, 0, 0, 0); // cursor bottom
		display((*a) * (*b));
		*state = 2;
		*a = 0;
		*b = 0;
	} else if (*state == 0 && r == '*') {
		write_to_IR(0, 0, 0, 0, 0, 0, 0, 0, 1); // clear
		*mode = 2;
		*state = 1;
	} else if (isdigit(r)) {
		if (*state == 1) {
			*b *= 10;
			*b += (r - '0');
			if (length(*b) == 8) {
				write_to_IR(0, 0, 0, 0, 0, 0, 0, 0, 1); // clear
				write_to_IR(0, 1, 1, 0, 0, 0, 0, 0, 0); // cursor bottom
				if (*mode == 0) { display((*a) + (*b)); }
				else if (*mode == 2) { display((*a) * (*b)); }
				*state = 0;
				*a = 0;
				*b = 0;
			} else {
				display(r - '0');
			}
		} else if (*state == 2) {
			write_to_IR(0, 0, 0, 0, 0, 0, 0, 0, 1); // clear
			write_to_IR(0, 1, 0, 0, 0, 0, 0, 0, 0); // cursor top
			display(r - '0');
			*state = 0;
			*mode = 2;
			*a = (r - '0');
		} else if (*state == 0) {
			*a *= 10;
			*a += (r - '0');
			if (length(*a) == 8) {
				*state = 1;
				*mode = 2;
				write_to_IR(0, 0, 0, 0, 0, 0, 0, 0, 1); // clear
				write_to_IR(0, 1, 0, 0, 0, 0, 0, 0, 0); // Set cursor line 1
			} else {
				display(r - '0');
			}
		}
	}
}

int main(void)
{
	keypad_init();
	LCD_init();
	setup();
	int a = 0;
	int b = 0;
	// 0 | A | add
	// 1 | C | subtract
	// 2 | * | multiply | default
	// 3 | D | divide
	int mode = 0;
	int state = 0;

	for(;;) {
		char result = keypad_response();
		if (result != '-') {
			input_handler(result, &a, &b, &state, &mode);
			for (int i = 0; i < 200000; ++i);
			while (keypad_response() != '-');
			for (int i = 0; i < 200000; ++i);
		}
	}
}
